### ISSUE TITLE
RPC does not work well.

### ISSUE THREAD

**Issue by Kenun99** [second-state/SOLL#119]
After I executed `docker run -it secondstate/devchain:devchain attach http://devchain-ewasm.secondstate.io:8545`, it seems that the RCP service at `http://devchain-ewasm.secondstate.io:8545` is offline.

**Comment by hydai** [comment]
Hi @Kenun99 
Thanks for trying our testnet. Because the `devchain-ewasm` is very old testnet (maybe two years ago). So we plan to upgrade it with the latest software. That's why it is shutdown.

And we will announce a branch new testnet RPC service in this Month. Once it launches, I will notify you. Thanks for your patience :-)

**Comment by hydai** [comment]
Hi @Kenun99 

Our new ewasm runtime is deployed on [ParaState network](https://www.parastate.io/).

For the faucet: https://testnet.faucet.parastate.io:8001/faucet
For the RPC gateway: https://rpc.parastate.io:8545

Please move forward to the new testnet, thanks.


If you have any question about the new testnet, please let me know, thanks.

**Comment by tpmccallum** [comment]
Hi @hydai 
Can we please look at the following error when starting devchain?

If we run
```bash
docker run -it secondstate/devchain:devchain attach https://rpc.parastate.io:8545
```
Then the following error is returned
```bash
Fatal: Failed to start the JavaScript console: api modules: Method not found
```

I think the solution is to add the following parameter when starting (restarting) the the RPC process on the rpc.parastate.io server.
```bash
--rpcvhosts=rpc.parastate.io
```

**Comment by hydai** [comment]
Hi @tpmccallum 
I think we should drop the `secondstate/devchain` image. This container uses `devchain` which is a modified geth client (with CyberMiles modifications). It will have some issues when connecting to the ethereum-compatible chain. Maybe you can try `ethereum/client-go`

**Comment by tpmccallum** [comment]
Hi @hydai 
Thanks!
I tried using `ethererum/client-go` and found that the ParaState RPC endpoint is still restricting clients from running `geth attach` against it.
Are we able to restart rpc.parastate whilst adding `--rpcvhosts=rpc.parastate.io` and also `--rpc --rpcaddr 0.0.0.0 --rpcport 8545`
Then I can try this again.
Thank you.

**Comment by hydai** [comment]
Great. The ParaState node is not from `geth` but from `frontier` which is the polkadot software stack. So it may need extra settings to make it compatible with `geth`. I will check these options.
