### ISSUE TITLE
Now we can generate eWASM smart contracts from EVM bytecode

### ISSUE THREAD

**Issue by Kenun99** [second-state/SOLL#125]
I implement an EVM-to-eWASM bytecode translator that can ensure the fidelity of translation. EVM bytecode contracts now can run in eWASM runtime directly. I also build a local blockchain and test the eWASM contracts. The results look nice. It is surprise that we can generate accurate LLVM bitcode even we do not have source code. 
Check [https://github.com/Kenun99/ethsema](https://github.com/Kenun99/ethsema) for more details.

**Comment by juntao** [comment]
Oh wow. That is cool! We will check it out!

**Comment by lwy0518** [comment]
@Kenun99 Hello, the link you sent cannot be found, can you re-send it?

**Comment by Kenun99** [comment]
https://github.com/ethsema/ethsema-paper
