### ISSUE TITLE
Cannot compile Ethereum smart contracts.

### ISSUE THREAD

**Issue by Coder2Programmer** [second-state/SOLL#2]
I just used soll to compile some smart contracts, such as https://github.com/gongbell/ContractFuzzer/blob/master/examples/delegatecall_dangerous/verified_contract_sols/CBToken.sol, https://github.com/gongbell/ContractFuzzer/blob/master/examples/delegatecall_dangerous/verified_contract_sols/DSProxy.sol

Unfortunately, most of compilation results are incorrect. The error occurred in the first phase, when a *.ll is generated(command is `~/soll/build/tools/soll/soll ./CBToken.sol > ./CBToken.ll`). The error message is as follow. Of course, the .sol is utf-8 encoded.
![image](https://user-images.githubusercontent.com/24288054/69031528-41a2ca00-0a15-11ea-9912-c88e588c2236.png)

Using command `~/soll/utils/compile -v ./CBToken.ll`, and the final .wasm bytecode is as follow.
![image](https://user-images.githubusercontent.com/24288054/69027085-968c1380-0a08-11ea-9339-245c9a2334be.png)

So I want to know the reason for this result, does the soll currently support compilation of most contracts?

**Comment by hydai** [comment]
Hi, thanks for using our SOLL compiler.

SOLL is still in early-stage development, and we support limited solidity features currently. Please refer to our [examples](https://github.com/second-state/soll/tree/master/doc/examples) and [changelog](https://github.com/second-state/soll/blob/master/Changelog.md) for more details.

For example, SOLL doesn't support the following things:
* Library declaration
* Modifier declaration
* Some special variable (like address.static_call)
* Contract inheritance

---

The output looks weird because SOLL will not generate the `(import "env" "solidity.main"...)` in compilation flow. I would like to know what is your commands to compile the contracts. Could you paste it?

P.S. Here is our [compilation pipeline](https://github.com/second-state/soll#25-compile-an-erc20-smart-contract).

**Comment by hydai** [comment]
1. SOLL doesn't support **multiple contracts declaration**, **modifier declaration**, and **contract inheritance**. So both of your contracts will not compile to valid LLVM IR files. We are going to implement more solidity syntax support in the upcoming release.

2. I found that these contracts are one line contract, which means the `//` will comment out the remaining part of the contracts. So these contracts are incomplete to SOLL which makes the error happened.

**Comment by Coder2Programmer** [comment]
> 1. SOLL doesn't support **multiple contracts declaration**, **modifier declaration**, and **contract inheritance**. So both of your contracts will not compile to valid LLVM IR files. We are going to implement more solidity syntax support in the upcoming release.
> 2. I found that these contracts are one line contract, which means the `//` will comment out the remaining part of the contracts. So these contracts are incomplete to SOLL which makes the error happened.

Thank you for your reply, and I will follow your suggestions for next attempt.

**Comment by Coder2Programmer** [comment]
After I executed commond `~/soll/build/tools/soll/soll ./Forwarder.sol > ./Forwarder.ll`, the terminal has the following error. 
![image](https://user-images.githubusercontent.com/24288054/69138805-5016e180-0afa-11ea-8772-fc478f06129f.png)
And the contract is at 
https://github.com/Coder2Programmer/wana/blob/master/contracts_ethereum/contract_sols/Forwarder
What is the possible reason?

**Comment by hydai** [comment]
@Coder2Programmer, 
We've released a new version [0.0.3](https://github.com/second-state/soll/releases/tag/0.0.3).
In this version, you will receive the error message about the root cause. For example, I compile [Forwarder](https://github.com/Coder2Programmer/wana/blob/master/contracts_ethereum/contract_sols/Forwarder) contract, and I received the error message here:

<img width="966" alt="螢幕截圖 2019-11-20 16 00 12" src="https://user-images.githubusercontent.com/2776756/69219931-dbea4580-0bae-11ea-8c4b-2884e97271d9.png">

**Comment by Coder2Programmer** [comment]
@hydai Thanks. And another error appeared when I try to compile new version. As follow,
![image](https://user-images.githubusercontent.com/24288054/69244673-52536b80-0be0-11ea-9495-1f51359ad614.png)

**Comment by hydai** [comment]
May I ask your environment?
We've never seen this error before.

Our docker image bases on Ubuntu 18.04 bionic and g++ 7.4.0.
And my personal environment is Ubuntu 19.04 disco and g++ 8.3.0.

**Comment by Coder2Programmer** [comment]
@hydai Thank you for your help, the problem was solved after the virtual machine reloaded. But there exists an unresolved problem, which is that the v3.0.0 can not be found.
![image](https://user-images.githubusercontent.com/24288054/69492814-3b639080-0ee2-11ea-9ef1-f4c16c0e9480.png)
So how can I checkout to v3.0.0?

**Comment by hydai** [comment]
@Coder2Programmer, please use `git checkout 0.0.3`.

**Comment by Coder2Programmer** [comment]
Ok, I'm surly checkout to 0.0.3 and rebuilding the source code, but the same error appear again.
![image](https://user-images.githubusercontent.com/24288054/69543644-0716cf80-0fc9-11ea-9a1c-353c381296a8.png)
Of course, the [Forwarder](https://github.com/Coder2Programmer/wana/blob/master/contracts_ethereum/contract_sols/Forwarder) has changed. Moreover, I want to know the supported solidity version of soll because there exist some smart contracts coded in old version.

**Comment by hydai** [comment]
1. SOLL support Solidity version 0.5.13.
2. Let me check the result again. I used your `Forwarder` contract and got the result with the error message.

**Comment by Coder2Programmer** [comment]
Thanks very much, the cause of the error may be my environment configuration.

**Comment by Coder2Programmer** [comment]
@hydai I have tried many times in the virtual machine environment, and segment fault often occur.  The current branch is 0.0.3 as follow. 
![image](https://user-images.githubusercontent.com/24288054/70232839-43e88080-1798-11ea-9627-c77078a9402b.png)
My environment is Ubuntu 18.04-64bit, the [ClassicCheck.sol](https://github.com/gongbell/ContractFuzzer/blob/master/examples/freezing_ether/verified_contract_sols/ClassicCheck.sol) can not be compiled. So I want to know the recommended compilation environment and the reason of above error. Thanks.

**Comment by hydai** [comment]
We encounter the same issue with your contract. Now we are going to figure out the root cause to fix.

**Comment by Coder2Programmer** [comment]
Thank you very mach!

**Comment by hydai** [comment]
Hi @Coder2Programmer 
We've released [0.0.5](https://github.com/second-state/SOLL/releases/tag/0.0.5). In this version, we fixed several bugs. 
I have tried to compile your [ClassicCheck.sol](https://github.com/gongbell/ContractFuzzer/blob/master/examples/freezing_ether/verified_contract_sols/ClassicCheck.sol) and retrieved the correct output .ll file.

**Comment by Coder2Programmer** [comment]
Thanks.
