### ISSUE TITLE
Error: Segmentation fault (core dumped)

### ISSUE THREAD

**Issue by q871795224** [second-state/SOLL#41]
When I use the solidity to ewasm function of soll, soll always reports an error “Segmentation fault (core dumped)“, is there any way to solve it?
The contract is as follows:
```
contract Caller {
    function callAddress(address a) {
        a.call();
    }
}
```
The command I used is:
```
root@6a562140ab6a:~/soll# ~/soll/build/tools/soll/soll Caller.sol
```
the result is:
```
Segmentation fault (core dumped)
```

**Comment by hydai** [comment]
Thanks for reporting this issue.

If you want to call a contract without any payload, please use `a.call("") instead.


In this case, soll should prints an error message about the there is no parameter provided.

According to solidity documents, `call` function should have a single bytes memory parameter.
https://solidity.readthedocs.io/en/v0.7.4/types.html#members-of-addresses

**Comment by q871795224** [comment]
It helps a lot, thanks you!
