### ISSUE TITLE
 solidity function does not support multiple return values

### ISSUE THREAD

**Issue by yp945** [second-state/SOLL#5]
When I try to return multiple values ​​in solidity, converting to ll file will give an error

**Comment by yp945** [comment]
pragma solidity ^0.5.0;
contract SetHash{
    mapping(bytes32 => bytes32) hashMap;


    function setHash(bytes32 key,bytes32 value) public returns(bool,bytes32){
        if(hashMap[key] != 0x0){
            return (false,"the key exist");
        }        
        hashMap[key] = value;
        return (true,"Success");
    }

    function setHashNoQuery(bytes32 key,bytes32 value) public returns(bool,bytes32){
        hashMap[key] = value;
        return (true,"Success");
    }

    function getHash(bytes32 key) public view returns(bool,bytes32,bytes32){
        if(hashMap[key] == 0x0){
            return (false,"the key is not exist",0x0);
        }
        return (true,"Success",hashMap[key]);
    }
}

**Comment by yp945** [comment]
`pragma solidity ^0.5.0;
contract SetHash{
    mapping(bytes32 => bytes32) hashMap;


    function setHash(bytes32 key,bytes32 value) public returns(bool,bytes32){
        if(hashMap[key] != 0x0){
            return (false,"the key exist");
        }        
        hashMap[key] = value;
        return (true,"Success");
    }

    function setHashNoQuery(bytes32 key,bytes32 value) public returns(bool,bytes32){
        hashMap[key] = value;
        return (true,"Success");
    }

    function getHash(bytes32 key) public view returns(bool,bytes32,bytes32){
        if(hashMap[key] == 0x0){
            return (false,"the key is not exist",0x0);
        }
        return (true,"Success",hashMap[key]);
    }
}
`

**Comment by yp945** [comment]
`pragma solidity ^0.5.0;
contract SetHash{
    mapping(bytes32 => bytes32) hashMap;
    function setHash(bytes32 key,bytes32 value) public returns(bool,bytes32){
        if(hashMap[key] != 0x0){
            return (false,"the key exist");
        }        
        hashMap[key] = value;
        return (true,"Success");
    }

    function setHashNoQuery(bytes32 key,bytes32 value) public returns(bool,bytes32){
        hashMap[key] = value;
        return (true,"Success");
    }

    function getHash(bytes32 key) public view returns(bool,bytes32,bytes32){
        if(hashMap[key] == 0x0){
            return (false,"the key is not exist",0x0);
        }
        return (true,"Success",hashMap[key]);
    }
}
`

**Comment by yp945** [comment]
pragma solidity ^0.5.0;
contract SetHash{
    mapping(bytes32 => bytes32) hashMap;
    function setHash(bytes32 key,bytes32 value) public returns(bool,bytes32){
        if(hashMap[key] != 0x0){
            return (false,"the key exist");
        }        
        hashMap[key] = value;
        return (true,"Success");
    }

    function setHashNoQuery(bytes32 key,bytes32 value) public returns(bool,bytes32){
        hashMap[key] = value;
        return (true,"Success");
    }

    function getHash(bytes32 key) public view returns(bool,bytes32,bytes32){
        if(hashMap[key] == 0x0){
            return (false,"the key is not exist",0x0);
        }
        return (true,"Success",hashMap[key]);
    }
}

**Comment by hydai** [comment]
SOLL supports only a return value now. Multiple return values is on our roadmap. We will fix this in the future release.
