### ISSUE TITLE
Some tests failed after 'pop' test enabled

### ISSUE THREAD

**Issue by eee4017** [second-state/SOLL#55]
These tests would fail after 'pop' related test is enabled in lit.cfg.py.

23:     SOLL :: libyul/functionSideEffects/structures.yul
23:     SOLL :: libyul/functionSideEffects/with_loop.yul
23:     SOLL :: libyul/yulOptimizerTests/commonSubexpressionEliminator/case2.yul
23:     SOLL :: libyul/yulOptimizerTests/commonSubexpressionEliminator/function_scopes.yul
23:     SOLL :: libyul/yulOptimizerTests/conditionalSimplifier/clear_after_if_break.yul
23:     SOLL :: libyul/yulOptimizerTests/conditionalSimplifier/clear_after_if_continue.yul
23:     SOLL :: libyul/yulOptimizerTests/conditionalSimplifier/opt_switch.yul
23:     SOLL :: libyul/yulOptimizerTests/conditionalUnsimplifier/clear_after_if_break.yul
23:     SOLL :: libyul/yulOptimizerTests/conditionalUnsimplifier/clear_after_if_continue.yul
23:     SOLL :: libyul/yulOptimizerTests/conditionalUnsimplifier/opt_switch.yul
23:     SOLL :: libyul/yulOptimizerTests/deadCodeEliminator/early_leave.yul
23:     SOLL :: libyul/yulOptimizerTests/deadCodeEliminator/function_after_revert.yul
23:     SOLL :: libyul/yulOptimizerTests/equivalentFunctionCombiner/multiple_complex.yul
23:     SOLL :: libyul/yulOptimizerTests/equivalentFunctionCombiner/simple_different_vars.yul
23:     SOLL :: libyul/yulOptimizerTests/fullInliner/pop_result.yul
23:     SOLL :: libyul/yulOptimizerTests/fullSimplify/not_applied_removes_non_constant_and_not_movable.yul
23:     SOLL :: libyul/yulOptimizerTests/fullSuite/medium.yul
23:     SOLL :: libyul/yulOptimizerTests/fullSuite/reuse_vars_bug_in_simplifier.yul
23:     SOLL :: libyul/yulOptimizerTests/fullSuite/stack_compressor_msize.yul
23:     SOLL :: libyul/yulOptimizerTests/loadResolver/memory_with_different_kinds_of_invalidation.yul
23:     SOLL :: libyul/yulOptimizerTests/rematerialiser/branches_for1.yul
23:     SOLL :: libyul/yulOptimizerTests/rematerialiser/branches_for2.yul
23:     SOLL :: libyul/yulOptimizerTests/rematerialiser/branches_if.yul
23:     SOLL :: libyul/yulOptimizerTests/rematerialiser/branches_switch.yul
23:     SOLL :: libyul/yulOptimizerTests/rematerialiser/reassign.yul
23:     SOLL :: libyul/yulOptimizerTests/rematerialiser/reassignment.yul
23:     SOLL :: libyul/yulOptimizerTests/stackCompressor/unusedPrunerWithMSize.yul
23:     SOLL :: libyul/yulOptimizerTests/unusedPruner/pop.yul

**Comment by eee4017** [comment]
#56

**Comment by hydai** [comment]
Fixed at #56
