### ISSUE TITLE
v0.0.4 cannot compile the .ll file

### ISSUE THREAD

**Issue by Coder2Programmer** [second-state/SOLL#7]
After v0.0.4 of soll was released, I updated and built local repo.  Unfortunately, I encountered an unexpected situation. My steps are as follow.

1. `git checkout 0.0.4` and build under docker environment.
2. Copy the test contract 0-0-3.sol to my test directory and rename it to "test.sol".
3. `~/soll/build/tools/soll/soll test.sol > test.ll`.
4. `~/soll/tools/compile -v test.ll`. **After a long time( >1 hour), the compilation process is still not complete.**
![image](https://user-images.githubusercontent.com/24288054/71554008-43b86980-2a54-11ea-988d-aa5ac70ef2fd.png)

Does the problem only appear on my computer?

**Comment by hydai** [comment]
Hi @Coder2Programmer,

Thanks for reporting this issue. Unfortunately, my personal environment, our internal CI, and our docker image don't encounter the same issue.

Our docker image:
<img width="1280" alt="螢幕截圖 2019-12-30 12 34 03" src="https://user-images.githubusercontent.com/2776756/71568250-cac31b80-2b00-11ea-9cb1-17713b8a882e.png">

My personal environment:
<img width="1280" alt="螢幕截圖 2019-12-30 12 30 43" src="https://user-images.githubusercontent.com/2776756/71568251-cac31b80-2b00-11ea-8973-b006a100f2c2.png">

Please check the following things to help us reproduce your issue:
1. Is the content of `test.ll` correct?
2. Please run those comments manually and check if there is any warning/error on the console.

**Comment by Coder2Programmer** [comment]
1. Yes, the test.ll is converted from 0.0.3.sol.
2. I ran those comments manually, and the same result appears.

**Comment by hydai** [comment]
Could you paste your test.ll?
If the output is correct, it will not take so much time.

**Comment by Coder2Programmer** [comment]
Thank you for your reply, the .ll file is at [0-0-3.ll](https://drive.google.com/file/d/1UH6cBPy_ahZdUNIn9FPnfx4lD-0oSqsT/view?usp=sharing)

**Comment by hydai** [comment]
Hi @Coder2Programmer 
I take your .ll file and compile it on a clean docker environment. It takes only few seconds. :-(
And I have tested its functionality, all of its functions work very well.
 
Please try to remove build folder and try again.

![螢幕截圖 2020-01-08 15 56 56](https://user-images.githubusercontent.com/2776756/71960302-9ef61300-322f-11ea-82bd-e5c44036fa70.png)

**Comment by Coder2Programmer** [comment]
@hydai  Thank you. I solved this problem by configuring the local environment instead instead of docker.
