### ISSUE TITLE
Cannot compile contract with structs and enums

### ISSUE THREAD

**Issue by andreibancioiu** [second-state/SOLL#9]
Hello!

Perhaps the following should be added to the [list of not yet supported features](https://github.com/second-state/SOLL/blob/master/doc/guides/FeatureGuideForSolidity.md)?

- structs (`error: 'struct' is not yet supported.`)
- enums (`error: 'enum' is not yet supported.`)

**Comment by hydai** [comment]
Thanks for reporting!
Yes, these should be on the not yet supported list.

**Comment by hydai** [comment]
Fixed at db6a68985ce0f4506207b7ba29a62eb583ee2de9
