### ISSUE TITLE
Can this tool convey solidity to LLVM IR?

### ISSUE THREAD

**Issue by TheKingShun** [second-state/SOLL#94]
can this tool convey solidity to LLVM IR?  
HOW?

**Comment by hydai** [comment]
Yes. You can use `EmitLLVM` option to generate `.ll` file.

https://github.com/second-state/SOLL/blob/3afc5f3b26f31c89839d0acf84f604a8f428a02f/include/soll/Frontend/FrontendOptions.h#L21

**Comment by TheKingShun** [comment]
@hydai Thx！！！！！！！！
 I did it
